

class InternalError(Exception):
    '''Exception raised when unexpected behaviour appeared'''
